export const IMAGE_MAP: Record<string, string> = {
  "거북왕": "blastoise",
  "리자몽": "charizard",
  "메가거북왕": "mega-blastoise",
  "메가리자몽": "mega-charizard",
  "메가뮤츠": "mega-mewtwo",
  "메가이상해꽃": "mega-venusaur",
  "몬스터볼로고": "pokeball-logo",
  "뮤츠": "mewtwo",
  "배틀필드2": "battlefield",
  "실행버튼": "start-button",
  "이상해꽃": "venusaur",
  "잔디배경": "grass-background",
  "전기에너지": "electric-energy",
  "체육관배지": "gym-badge",
  "포켓몬로고": "pokemon-logo",
  "개무소": "wormple",
  "나옹": "meowth",
  "내루미": "lickitung",
  "데스마스": "yamask",
  "따라큐": "mimikyu",
  "또가스": "koffing",
  "로사": "jessie",
  "로사로이": "Jessie_and_James",
  "로이": "james",
  "로켓단로고": "rocket_logo",
  "마자용": "wobbuffet",
  "메가자리": "yanmega",
  "모르페코": "morpeko",
  "선인왕": "cacnea",
  "세비퍼": "seviper",
  "셀러": "shellder",
  "아보크": "arbok",
  "우츠동": "weepinbell",
  "흉내내": "mime_jr",
  "거북왕노말폼": "blastoise_normalform",
  "거북왕메가진화폼": "blastoise_megaform",
  "리자몽노말폼": "charizard_normalform",
  "리자몽메가진화폼": "charizard_megaform",
  "뮤츠노말폼": "mewtwo_normalform",
  "뮤츠메가진화폼": "mewtwo_megaform",
  "이상해꽃노말폼": "venusaur_normalform",
  "이상해꽃메가진화폼": "venusaur_megaform",
};

export const ICON_MAP: Record<string, string> = {
  "대기 중": "waiting_icon",
  "대기중아이콘.png": "waiting_icon.png",
  "레디큐아이콘.png": "readyqueue_icon.png",
  "우리팀아이콘.png": "team_icon.png",
  "전투 중": "fighting_icon",
  "전투중아이콘.png": "fighting_icon.png",
  "접근 중": "coming_icon",
  "접근중아이콘.png": "coming_icon.png",
  "종료": "finish_icon",
  "종료아이콘.png": "finish_icon.png",
  "waiting-icon.png": "waiting_icon.png",
  "end-icon.png": "finish_icon.png",
  "battle-icon.png": "fighting_icon.png",
  "approach-icon.png": "coming_icon.png",
};

export const CORE_MAPPING: Record<number, { name: string; icon: string; megaIcon: string; standing: string; megaStanding: string; color: string; accent: string }> = {
  0: {
    name: "리자몽",
    icon: "/images/charizard.png",
    megaIcon: "/images/mega-charizard.png",
    standing: "/images/standing/charizard_normalform.gif",
    megaStanding: "/images/standing/charizard_megaform.gif",
    color: "#fee2e2",
    accent: "#ef4444",
  },
  1: {
    name: "이상해꽃",
    icon: "/images/venusaur.png",
    megaIcon: "/images/mega-venusaur.png",
    standing: "/images/standing/venusaur_normalform.gif",
    megaStanding: "/images/standing/venusaur_megaform.gif",
    color: "#f0fdf4",
    accent: "#22c55e",
  },
  2: {
    name: "거북왕",
    icon: "/images/blastoise.png",
    megaIcon: "/images/mega-blastoise.png",
    standing: "/images/standing/blastoise_normalform.gif",
    megaStanding: "/images/standing/blastoise_megaform.gif",
    color: "#eff6ff",
    accent: "#3b82f6",
  },
  3: {
    name: "뮤츠",
    icon: "/images/mewtwo.png",
    megaIcon: "/images/mega-mewtwo.png",
    standing: "/images/standing/mewtwo_normalform.gif",
    megaStanding: "/images/standing/mewtwo_megaform.gif",
    color: "#f5f3ff",
    accent: "#8b5cf6",
  },
};

export const PROCESS_NAME_MAPPING: Record<string, string> = {
  P1: "나옹",
  P2: "아보크",
  P3: "마자용",
  P4: "셀러",
  P5: "내루미",
  P6: "또가스",
  P7: "우츠동",
  P8: "선인왕",
  P9: "데스마스",
  P10: "흉내내",
  P11: "모르페코",
  P12: "세비퍼",
  P13: "따라큐",
  P14: "개무소",
  P15: "메가자리",
};

export const getPokemonName = (pId: string) => PROCESS_NAME_MAPPING[pId] || pId;
export const getPokemonIcon = (pId: string) => {
  const name = PROCESS_NAME_MAPPING[pId] || pId;
  const englishName = IMAGE_MAP[name] || name;
  return `/images/rocket/${englishName}.png`;
};

export const getCoreInfo = (coreId: number) => CORE_MAPPING[coreId];
